# Generated by Django 6.0.3 on 2026-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AILegal', '0005_constitution_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
