# Generated by Django 4.2.7 on 2026-07-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AILegal', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NyayaEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('lawyer_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('case_situation', models.TextField(blank=True, default='')),
                ('urgency', models.CharField(blank=True, default='Normal', max_length=50)),
                ('specific_ask', models.TextField(blank=True, default='')),
                ('attachments_json', models.JSONField(default=list)),
                ('suggested_actions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nyaya_email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nyaya_email_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
