# Generated by Django 4.2.7 on 2026-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AILegal', '0009_bareactamendment_permission_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('lawyer', 'Lawyer'), ('advocate', 'Advocate'), ('citizen', 'Citizen'), ('user', 'User')], default='citizen', max_length=20),
        ),
    ]
