# Generated by Django 4.2.7 on 2026-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AILegal', '0010_user_auth_provider_user_google_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
