// Build-time fetch of published posts from Notra (https://usenotra.com).
//
// Writes src/lib/notra-posts.generated.ts, which the blog reads synchronously so
// the API key never ships to the browser and there are no client -> Notra calls.
// Run automatically before `vite build`, or on demand via `bun run posts:fetch`.
//
// Resilient by design: a missing key or a Notra outage keeps the last committed
// snapshot instead of wiping the blog, and never fails the build.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { Notra } from "@usenotra/sdk";

import type { BlogPost } from "../src/lib/blog-types";
import { mapNotraPost, type NotraPostInput } from "./notra-content";

const outputFile = join(import.meta.dirname, "../src/lib/notra-posts.generated.ts");
const pageSize = 100;

async function fetchPublishedPosts(notra: Notra): Promise<NotraPostInput[]> {
  const posts: NotraPostInput[] = [];
  let page = 1;

  for (;;) {
    const response = await notra.content.listPosts({
      status: "published",
      sort: "desc",
      limit: pageSize,
      page,
    });

    posts.push(...(response.posts as NotraPostInput[]));

    const nextPage = response.pagination?.nextPage;
    if (!nextPage) break;
    page = nextPage;
  }

  return posts;
}

function serialize(posts: BlogPost[], bodies: Record<string, string>): string {
  return `// AUTO-GENERATED by scripts/fetch-notra-posts.ts — do not edit by hand.
// Source of truth: Notra (https://usenotra.com). Regenerated on every build.
import type { BlogPost } from "./blog-types";

export const notraPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export const notraPostBodies: Record<string, string> = ${JSON.stringify(bodies, null, 2)};
`;
}

function writeGenerated(posts: BlogPost[], bodies: Record<string, string>): void {
  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, serialize(posts, bodies));
}

function ensureFileExists(): void {
  if (!existsSync(outputFile)) writeGenerated([], {});
}

async function main(): Promise<void> {
  const apiKey = process.env.NOTRA_API_KEY?.trim();

  if (!apiKey) {
    console.warn(
      "[notra] NOTRA_API_KEY is not set — skipping fetch and keeping the existing blog snapshot.",
    );
    ensureFileExists();
    return;
  }

  try {
    const notra = new Notra({ bearerAuth: apiKey });
    const rawPosts = await fetchPublishedPosts(notra);

    const seenSlugs = new Set<string>();
    const posts: BlogPost[] = [];
    const bodies: Record<string, string> = {};

    for (const raw of rawPosts) {
      const mapped = mapNotraPost(raw, seenSlugs);
      if (!mapped) continue;

      posts.push(mapped.post);
      bodies[mapped.post.slug] = mapped.html;
    }

    posts.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
    writeGenerated(posts, bodies);

    console.log(
      `[notra] wrote ${posts.length} published post(s) to src/lib/notra-posts.generated.ts`,
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`[notra] fetch failed (${message}); keeping the existing blog snapshot.`);
    ensureFileExists();
  }
}

await main();
