/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsDotmdRouteImport } from './routes/llms[.]md'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as IndexDotmdRouteImport } from './routes/index[.]md'
import { Route as FeedDotjsonRouteImport } from './routes/feed[.]json'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsEmailDnsCheckerRouteImport } from './routes/tools/email-dns-checker'
import { Route as FeedsDocsDotjsonlRouteImport } from './routes/feeds/docs[.]jsonl'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsLlmsDottxtRouteImport } from './routes/docs/llms[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ComparePairRouteImport } from './routes/compare/$pair'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiBuildInfoRouteImport } from './routes/api/build-info'
import { Route as OgBlogSplatRouteImport } from './routes/og/blog/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdRoute = LlmsDotmdRouteImport.update({
  id: '/llms.md',
  path: '/llms.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDotmdRoute = IndexDotmdRouteImport.update({
  id: '/index.md',
  path: '/index.md',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotjsonRoute = FeedDotjsonRouteImport.update({
  id: '/feed.json',
  path: '/feed.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEmailDnsCheckerRoute = ToolsEmailDnsCheckerRouteImport.update({
  id: '/tools/email-dns-checker',
  path: '/tools/email-dns-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsDocsDotjsonlRoute = FeedsDocsDotjsonlRouteImport.update({
  id: '/feeds/docs.jsonl',
  path: '/feeds/docs.jsonl',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDottxtRoute = DocsLlmsDottxtRouteImport.update({
  id: '/docs/llms.txt',
  path: '/docs/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePairRoute = ComparePairRouteImport.update({
  id: '/compare/$pair',
  path: '/compare/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildInfoRoute = ApiBuildInfoRouteImport.update({
  id: '/api/build-info',
  path: '/api/build-info',
  getParentRoute: () => rootRouteImport,
} as any)
const OgBlogSplatRoute = OgBlogSplatRouteImport.update({
  id: '/og/blog/$',
  path: '/og/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.md': typeof LlmsDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/api/build-info': typeof ApiBuildInfoRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$pair': typeof ComparePairRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/feeds/docs.jsonl': typeof FeedsDocsDotjsonlRoute
  '/tools/email-dns-checker': typeof ToolsEmailDnsCheckerRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/og/blog/$': typeof OgBlogSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.md': typeof LlmsDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/api/build-info': typeof ApiBuildInfoRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$pair': typeof ComparePairRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/feeds/docs.jsonl': typeof FeedsDocsDotjsonlRoute
  '/tools/email-dns-checker': typeof ToolsEmailDnsCheckerRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/og/blog/$': typeof OgBlogSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/index.md': typeof IndexDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.md': typeof LlmsDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/api/build-info': typeof ApiBuildInfoRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$pair': typeof ComparePairRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/feeds/docs.jsonl': typeof FeedsDocsDotjsonlRoute
  '/tools/email-dns-checker': typeof ToolsEmailDnsCheckerRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/og/blog/$': typeof OgBlogSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/feed.json'
    | '/index.md'
    | '/llms-full.txt'
    | '/llms.md'
    | '/llms.txt'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/api/build-info'
    | '/api/search'
    | '/blog/$slug'
    | '/compare/$pair'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/feeds/docs.jsonl'
    | '/tools/email-dns-checker'
    | '/blog/'
    | '/compare/'
    | '/tools/'
    | '/og/blog/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/feed.json'
    | '/index.md'
    | '/llms-full.txt'
    | '/llms.md'
    | '/llms.txt'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/api/build-info'
    | '/api/search'
    | '/blog/$slug'
    | '/compare/$pair'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/feeds/docs.jsonl'
    | '/tools/email-dns-checker'
    | '/blog'
    | '/compare'
    | '/tools'
    | '/og/blog/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/feed.json'
    | '/index.md'
    | '/llms-full.txt'
    | '/llms.md'
    | '/llms.txt'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/api/build-info'
    | '/api/search'
    | '/blog/$slug'
    | '/compare/$pair'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/feeds/docs.jsonl'
    | '/tools/email-dns-checker'
    | '/blog/'
    | '/compare/'
    | '/tools/'
    | '/og/blog/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeedDotjsonRoute: typeof FeedDotjsonRoute
  IndexDotmdRoute: typeof IndexDotmdRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDotmdRoute: typeof LlmsDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  ApiBuildInfoRoute: typeof ApiBuildInfoRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ComparePairRoute: typeof ComparePairRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsDottxtRoute: typeof DocsLlmsDottxtRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  FeedsDocsDotjsonlRoute: typeof FeedsDocsDotjsonlRoute
  ToolsEmailDnsCheckerRoute: typeof ToolsEmailDnsCheckerRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  OgBlogSplatRoute: typeof OgBlogSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.md': {
      id: '/llms.md'
      path: '/llms.md'
      fullPath: '/llms.md'
      preLoaderRoute: typeof LlmsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.md': {
      id: '/index.md'
      path: '/index.md'
      fullPath: '/index.md'
      preLoaderRoute: typeof IndexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.json': {
      id: '/feed.json'
      path: '/feed.json'
      fullPath: '/feed.json'
      preLoaderRoute: typeof FeedDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/email-dns-checker': {
      id: '/tools/email-dns-checker'
      path: '/tools/email-dns-checker'
      fullPath: '/tools/email-dns-checker'
      preLoaderRoute: typeof ToolsEmailDnsCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/docs.jsonl': {
      id: '/feeds/docs.jsonl'
      path: '/feeds/docs.jsonl'
      fullPath: '/feeds/docs.jsonl'
      preLoaderRoute: typeof FeedsDocsDotjsonlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.txt': {
      id: '/docs/llms.txt'
      path: '/docs/llms.txt'
      fullPath: '/docs/llms.txt'
      preLoaderRoute: typeof DocsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$pair': {
      id: '/compare/$pair'
      path: '/compare/$pair'
      fullPath: '/compare/$pair'
      preLoaderRoute: typeof ComparePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build-info': {
      id: '/api/build-info'
      path: '/api/build-info'
      fullPath: '/api/build-info'
      preLoaderRoute: typeof ApiBuildInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/blog/$': {
      id: '/og/blog/$'
      path: '/og/blog/$'
      fullPath: '/og/blog/$'
      preLoaderRoute: typeof OgBlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeedDotjsonRoute: FeedDotjsonRoute,
  IndexDotmdRoute: IndexDotmdRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDotmdRoute: LlmsDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  ApiBuildInfoRoute: ApiBuildInfoRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  ComparePairRoute: ComparePairRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsDottxtRoute: DocsLlmsDottxtRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  FeedsDocsDotjsonlRoute: FeedsDocsDotjsonlRoute,
  ToolsEmailDnsCheckerRoute: ToolsEmailDnsCheckerRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  OgBlogSplatRoute: OgBlogSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
