// AUTO-GENERATED by scripts/fetch-notra-posts.ts — do not edit by hand.
// Source of truth: Notra (https://usenotra.com). Regenerated on every build.
import type { BlogPost } from "./blog-types";

export const notraPosts: BlogPost[] = [];

export const notraPostBodies: Record<string, string> = {};
