export const providers = [
  {
    name: "Resend",
    key: "resend",
    importPath: "@opencoredev/email-sdk/resend",
    docs: "/docs/adapters/resend",
    website: "https://resend.com",
    logo: "/og/provider-logos/resend-mark.svg",
    invertOnDark: true,
  },
  {
    name: "Postmark",
    key: "postmark",
    importPath: "@opencoredev/email-sdk/postmark",
    docs: "/docs/adapters/postmark",
    website: "https://postmarkapp.com",
    logo: "https://www.google.com/s2/favicons?domain=postmarkapp.com&sz=64",
  },
  {
    name: "SendGrid",
    key: "sendgrid",
    importPath: "@opencoredev/email-sdk/sendgrid",
    docs: "/docs/adapters/sendgrid",
    website: "https://sendgrid.com",
    logo: "https://www.google.com/s2/favicons?domain=sendgrid.com&sz=64",
  },
  {
    name: "AWS SES",
    key: "ses",
    importPath: "@opencoredev/email-sdk/ses",
    docs: "/docs/adapters/ses",
    website: "https://aws.amazon.com/ses/",
    logo: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=64",
  },
  {
    name: "Mailgun",
    key: "mailgun",
    importPath: "@opencoredev/email-sdk/mailgun",
    docs: "/docs/adapters/mailgun",
    website: "https://www.mailgun.com",
    logo: "https://cdn.simpleicons.org/mailgun",
  },
  {
    name: "MailerSend",
    key: "mailersend",
    importPath: "@opencoredev/email-sdk/mailersend",
    docs: "/docs/adapters/mailersend",
    website: "https://www.mailersend.com",
    logo: "https://www.google.com/s2/favicons?domain=mailersend.com&sz=64",
  },
  {
    name: "Brevo",
    key: "brevo",
    importPath: "@opencoredev/email-sdk/brevo",
    docs: "/docs/adapters/brevo",
    website: "https://www.brevo.com",
    logo: "https://cdn.simpleicons.org/brevo",
  },
  {
    name: "Mailchimp Transactional",
    key: "mailchimp",
    importPath: "@opencoredev/email-sdk/mailchimp",
    docs: "/docs/adapters/mailchimp",
    website: "https://mailchimp.com/features/transactional-email",
    logo: "https://cdn.simpleicons.org/mailchimp",
  },
  {
    name: "SparkPost",
    key: "sparkpost",
    importPath: "@opencoredev/email-sdk/sparkpost",
    docs: "/docs/adapters/sparkpost",
    website: "https://www.sparkpost.com",
    logo: "https://cdn.simpleicons.org/sparkpost",
  },
  {
    name: "Mailtrap",
    key: "mailtrap",
    importPath: "@opencoredev/email-sdk/mailtrap",
    docs: "/docs/adapters/mailtrap",
    website: "https://mailtrap.io",
    logo: "https://cdn.simpleicons.org/mailtrap",
  },
  {
    name: "Cloudflare Email Sending",
    key: "cloudflare",
    importPath: "@opencoredev/email-sdk/cloudflare",
    docs: "/docs/adapters/cloudflare",
    website: "https://developers.cloudflare.com/email-service/",
    logo: "https://cdn.simpleicons.org/cloudflare",
  },
  {
    name: "Unosend",
    key: "unosend",
    importPath: "@opencoredev/email-sdk/unosend",
    docs: "/docs/adapters/unosend",
    website: "https://www.unosend.co",
    logo: "/provider-logos/unosend.svg",
    invertOnDark: true,
    currentOnly: true,
  },
  {
    name: "Scaleway",
    key: "scaleway",
    importPath: "@opencoredev/email-sdk/scaleway",
    docs: "/docs/adapters/scaleway",
    website: "https://www.scaleway.com/en/transactional-email-tem",
    logo: "https://cdn.simpleicons.org/scaleway",
  },
  {
    name: "ZeptoMail",
    key: "zeptomail",
    importPath: "@opencoredev/email-sdk/zeptomail",
    docs: "/docs/adapters/zeptomail",
    website: "https://www.zoho.com/zeptomail",
    logo: "https://cdn.simpleicons.org/zoho",
  },
  {
    name: "MailPace",
    key: "mailpace",
    importPath: "@opencoredev/email-sdk/mailpace",
    docs: "/docs/adapters/mailpace",
    website: "https://mailpace.com",
    logo: "https://www.google.com/s2/favicons?domain=mailpace.com&sz=64",
  },
  {
    name: "Iterable",
    key: "iterable",
    importPath: "@opencoredev/email-sdk/iterable",
    docs: "/docs/adapters/iterable",
    website: "https://iterable.com",
    logo: "https://www.google.com/s2/favicons?domain=iterable.com&sz=64",
    currentOnly: true,
  },
  {
    name: "Loops",
    key: "loops",
    importPath: "@opencoredev/email-sdk/loops",
    docs: "/docs/adapters/loops",
    website: "https://loops.so",
    logo: "https://cdn.simpleicons.org/loops",
  },
  {
    name: "Sequenzy",
    key: "sequenzy",
    importPath: "@opencoredev/email-sdk/sequenzy",
    docs: "/docs/adapters/sequenzy",
    website: "https://www.sequenzy.com/",
    logo: "/og/provider-logos/sequenzy.jpeg",
    currentOnly: true,
  },
  {
    name: "JetEmail",
    key: "jetemail",
    importPath: "@opencoredev/email-sdk/jetemail",
    docs: "/docs/adapters/jetemail",
    website: "https://jetemail.com",
    logo: "/og/provider-logos/jetemail.jpeg",
    currentOnly: true,
  },
  {
    name: "Primitive",
    key: "primitive",
    importPath: "@opencoredev/email-sdk/primitive",
    docs: "/docs/adapters/primitive",
    website: "https://www.primitive.dev",
    logo: "/og/provider-logos/primitive.png",
    currentOnly: true,
  },
  {
    name: "Lettermint",
    key: "lettermint",
    importPath: "@opencoredev/email-sdk/lettermint",
    docs: "/docs/adapters/lettermint",
    website: "https://lettermint.co",
    logo: "/og/provider-logos/lettermint.png",
    currentOnly: true,
  },
  {
    name: "Plunk",
    key: "plunk",
    importPath: "@opencoredev/email-sdk/plunk",
    docs: "/docs/adapters/plunk",
    website: "https://www.useplunk.com",
    logo: "https://www.google.com/s2/favicons?domain=useplunk.com&sz=64",
  },
  {
    name: "SMTP",
    key: "smtp",
    importPath: "@opencoredev/email-sdk/smtp",
    docs: "/docs/adapters/smtp",
    website: "https://datatracker.ietf.org/doc/html/rfc5321",
    logo: "",
  },
] as const;

export type Provider = (typeof providers)[number];
